- hosts: all
  become: yes
  tasks:
    - name: Install common packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - wget
          - htop
          - git
          - net-tools

- hosts: node-1
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Set up WordPress
      # Add tasks to set up WordPress with Docker

- hosts: node-2
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

